INSERT INTO
  ingredients
  (title, type, image),
VALUES
  ('butter', 'other', 'butter.jpg'),
  ('flour', 'other', 'flour.jpg'),
  ('baking powder', 'other', 'baking_powder.jpg'),
  ('egg', 'other', 'egg.jpg'),
  ('brown sugar', 'other', 'brown.jpg'),
  ('vanilla', 'other', 'vanilla.jpg'),
  ('water', 'other', 'water.jpg'),
  ('corn syrup', 'other', 'corn.jpg'),
  ('yeast', 'other', 'yeast.jpg'),
  ('pasta', 'other', 'pasta.jpg'),
  ('olive oil', 'other', 'olive.jpg'),
  ('garlic', 'other', 'garlic.jpg'),
  ('asparagus', 'vegetable', 'asparagus.jpg'),
  ('broth', 'other', 'broth.jpg'),
  ('dill', 'other', 'dill.jpg'),
  ('avocado', 'vegetable', 'avocado.jpg'),
  ('lime', 'fruit', 'lime.jpg'),
  ('garlic powder', 'other', 'garlic.jpg'),
  ('cheese', 'other', 'cheese.jpg'),
  ('vinegar', 'other', 'vinegar.jpg'),
  ('jelly', 'other', 'jelly.jpg'),
  ('blackberry', 'fruit', 'blackberry.jpg'),
  ('celery', 'vegetable', 'celery.jpg'),
  ('milk', 'other', 'milk.jpg'),
  ('apples', 'other', 'apples.jpg'),
  ('lemon', 'fruit', 'lemon.jpg'),
  ('raisins', 'other', 'raisins.jpg'),
  ('yogurt', 'other', 'yogurt.jpg'),
  ('walnuts', 'other', 'walnuts.jpg'),
  ('cinnamon', 'other', 'ground.jpg'),
  ('vegetable oil', 'other', 'vegetable.jpg'),
  ('pork', 'meat', 'pork.jpg'),
  ('soy sauce', 'other', 'soy.jpg'),
  ('brown sugar', 'other', 'brown.jpg'),
  ('vegetable oil', 'other', 'vegetable.jpg'),
  ('red pepper flakes', 'other', 'red.jpg'),
  ('cornstarch', 'other', 'cornstarch.jpg'),
  ('cocoa powder', 'other', 'cocoa.jpg'),
  ('baking soda', 'other', 'baking.jpg'),
  ('coffee', 'other', 'coffee.jpg'),
  ('cherry liqueur', 'other', 'cherry.jpg'),
  ('black beans', 'vegetable', 'black.jpg'),
  ('breadcrumbs', 'other', 'breadcrumbs.jpg'),
  ('chili powder', 'other', 'chili.jpg'),
  ('hot sauce', 'other', 'hot.jpg'),
  ('bread', 'other', 'bread.jpg'),
  ('mayonnaise', 'other', 'mayonnaise.jpg'),
  ('lettuce', 'vegetable', 'lettuce.jpg'),
  ('sweet potato', 'vegetable', ' sweet.jpg'),
  ('squash', 'vegetable', 'squash.jpg'),
  ('sage', 'other', 'sage.jpg'),
  ('garlic salt', 'other', 'garlic.jpg'),
  ('water chestnuts', 'vegetable', 'water.jpg'),
  ('rice', 'other', 'rice.jpg'),
  ('crackers', 'other', 'crackers.jpg'),
  ('almonds', 'other', 'almonds.jpg'),
  ('raisins', 'fruit', 'raisins.jpg'),
  ('ketchup', 'other', 'ketchup.jpg'),
  ('horseradish', 'other', 'horseradish.jpg'),
  ('paprika', 'other', 'paprika.jpg'),
  ('oregano', 'other', 'oregano.jpg'),
  ('cayenne pepper', 'other', 'cayenne.jpg'),
  ('powdered sugar', 'other', 'powdered.jpg'),
  ('marshmallow creme', 'other', 'marshmallow.jpg'),
  ('shallot', 'vegetable', 'shallot.jpg'),
  ('mushroom', 'vegetable', 'mushroom.jpg'),
  ('wine', 'other', 'wine.jpg'),
  ('cumin', 'other', 'cumin.jpg'),
  ('parsley', 'other', 'parsley.jpg'),
  ('lamb', 'meat', 'lamb.jpg'),
  ('club soda', 'other', 'club.jpg'),
  ('garbanzo beans', 'other', 'garbanzo.jpg'),
  ('cilantro', 'other', 'cilantro.jpg'),
  ('tahini', 'other', 'tahini.jpg'),
  ('jalapeno pepper', 'vegetable', ' jalapeno.jpg'),
  ('beet', 'vegetable', 'beet.jpg'),
  ('pear', 'fruit', 'pear.jpg'),
  ('cranberries', 'fruit', 'cranberries.jpg'),
  ('duck', 'meat', 'duck.jpg'),
  ('thyme', 'other', 'thyme.jpg'),
  ('peanut butter', 'other', 'peanut.jpg'),
  ('almond extract', 'other', 'almond.jpg'),
  ('bulgur', 'other', 'bulgur.jpg'),
  ('mint', 'other', 'mint.jpg'),
  ('green onion', 'other', 'green.jpg'),
  ('cornstarch', 'other', 'cornstarch.jpg'),
  ('tempeh', 'other', 'tempeh.jpg'),
  ('sauerkraut', 'vegetable', 'sauerkraut.jpg'),
  ('thousand island salad dressing', 'other', 'thousand.jpg'),
  ('sweet pickle relish', 'vegetable', 'sweet.jpg'),
  ('tarragon', 'other', 'tarragon.jpg'),
  ('lemon pepper', 'other', 'lemon.jpg'),
  ('Worcestershire sauce', 'other', 'Worcestershire.jpg'),
  ('bay leaves', 'other', 'bay.jpg'),
  ('leek', 'vegetable', 'leek.jpg'),
  ('spinach', 'vegetable', 'spinach.jpg'),
  ('sesame seeds, toasted', 'other', 'sesame.jpg'),
  ('mustard', 'other', 'mustard.jpg'),
  ('pine nuts', 'other', 'pine.jpg'),
  ('flax seed', 'other', 'flax.jpg'),
  ('gin', 'other', 'gin.jpg'),
  ('rosemary', 'other', 'rosemary.jpg'),
  ('zucchini', 'vegetable', 'zucchini.jpg');
